### ISSUE TITLE
Product Model (Django) and Database Schema / Paul Aderoju / Full Stack 

### ISSUE THREAD

**Issue by Saad-Saheed** [zuri-training/Team_21-Price-Compare#2]

**Comment by PaulBoye-py** [comment]
UPDATED MODELS, ADDED A MEDIA FOLDER, REGISTERED THE NEW MODELS ON ADMIN.

-I updated the models.py to include models for Product, Categories, Store and Wishlist.
-Added a media folder and configured the media folder on settings.py and urls.py(PriceBetaProject) to inform Django about the media folder that was created.
-Registered the new models on admin.py
-Updated the views.py
