### ISSUE TITLE
FOREVER OBASEKI (EVER) TASKS 

### ISSUE THREAD

**Issue by Seunlijadu** [zuri-training/Team_21-Price-Compare#26]
DESKTOP SCREEN
-GENERAL  DESIGN FOR ACCESSORY CATEGORY PAGE 1 AND 2
https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=839%3A3433
https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1059%3A1913

MOBILE SCREEN
-GENERAL DESIGN FOR ACCESSORY CATEGORY PAGE  2
https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1186%3A1684

STYLE GUIDE
-Color Style : https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1182%3A4584
-Buttons: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1182%3A4016

**Comment by EverObas** [comment]
Done

**Comment by EverObas** [comment]
DESKTOP SCREEN
-GENERAL  DESIGN FOR ACCESSORY CATEGORY PAGE 1 AND 2
https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=839%3A3433
https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1059%3A1913

MOBILE SCREEN
-GENERAL DESIGN FOR ACCESSORY CATEGORY PAGE  2
https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1186%3A1684

STYLE GUIDE
-Color Style : https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1182%3A4584
-Buttons: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1182%3A4016
