### ISSUE TITLE
 SHERIFATSHE2 TASKS

### ISSUE THREAD

**Issue by Seunlijadu** [zuri-training/Team_21-Price-Compare#27]
USER RESEARCH
EMPATHY MAP
USER PERSONA
DESKTOP ACCESSORY DESIGN PAGE 2 AND 3
MOBILE SCREEN DESIGN FOR PROFILE, WISHLIST  AND REVIEW PAGE

**Comment by sherifatshe2** [comment]
1. Desktop Accessory Design Page 3: https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=839%3A6053

2. User Research: https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=3%3A3304

3. Empathy Map: https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=219%3A1941

4. User Persona: https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=220%3A1960

5. Mobile Screen Design(Profile): https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=1185%3A1615

6. Mobile Screen Design(Wish list): https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=1182%3A1945

7. Mobile Screen Design(Review): https://www.figma.com/file/2Rm18o3n7a86AcfpdZgrYF/PriceBeta?node-id=1182%3A3298
