### ISSUE TITLE
OLAITAN BELLO (OLARH08) TASKS || PRODUCT DESIGN

### ISSUE THREAD

**Issue by Seunlijadu** [zuri-training/Team_21-Price-Compare#30]
DESKTOP  DESIGN
- Homepage header: 
- Top Navigation Bar: 
- Footer: 
- Gif and Logo design: 
- Sidebar 1: 
- Sidebar 2: 

USER RESEARCH
-  Survey questions: 
-  Data collation: 

MOBILE DESIGNS
- General design for homepage:
- Laptop category : 
- Accessories page 1: 
- Accessories page 3: 
- Mobile Category: 

STYLE GUIDE
- Iconography: 
- Color Style:

**Comment by Bells-8** [comment]
Homepage header: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1118%3A1925

**Comment by Seunlijadu** [comment]
hi Ola copy and paste this "homepage header...." u have immediately above this comment, in the first comment section with multiple links

**Comment by Bells-8** [comment]
DESKTOP DESIGN
- Homepage header: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1118%3A1925
- Top Navigation Bar: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1121%3A2650
- Footer: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=839%3A2422
- Gif and Logo design: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1118%3A1926
- Sidebar 1: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=850%3A2325
- Sidebar 2: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=850%3A2535


USER RESEARCH
-  Survey questions: https://forms.gle/pWdQBSKEP6cJhDNG9
-  Data collation: https://docs.google.com/forms/d/1aPsW2jNk9xi9GoTGvmWx-FxQ9w_jMwcqeYdYyyE9718/edit?usp=sharing


MOBILE DESIGNS
- General design for homepage: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=839%3A6498  
- Laptop category : https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=839%3A6713
- Accessories page 1: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1111%3A2535
- Accessories page 3: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1144%3A2244
- Mobile Category: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1111%3A1842


STYLE GUIDE
- Iconography: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1182%3A4043
- Color Style: https://www.figma.com/file/NL63Q6vRxWSsR6KVSyXwXl/PriceBeta-(Copy)?node-id=1182%3A4584
