### ISSUE TITLE
Database Schema, JavaScript implementation and Sign Up page  / Hephzihub / Full Stack

### ISSUE THREAD

**Issue by Saad-Saheed** [zuri-training/Team_21-Price-Compare#4]

**Comment by Hephzihub** [comment]
The database schema was drawn.

below is the ink to the drawing
![photo_2022-08-10_07-36-22](https://user-images.githubusercontent.com/64655766/184030281-4c3cb806-2364-4454-913d-ec7cd0636ecf.jpg)
n
